// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('tmsApp').controller('RegisterCtrl', [
    '$scope',
    function($scope) {
      $scope.userEntity = {
        username: '',
        password: '',
        password2: ''
      };
      return $scope.doRegister = function() {
        return console.log($scope.userEntity);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=registerCtrl.js.map
