// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('tmsApp').controller('LoginCtrl', [
    '$scope', '$location',
    function($scope, $location) {
      $scope.userEntity = {
        username: '',
        password: ''
      };
      $scope.rememberMe = false;
      return $scope.doLogin = function() {
        console.log($scope.userEntity);
        return $location.path('/').replace();
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=loginCtrl.js.map
